name: HouseofDB
favicon: null
layout_spectrum: 0.25327
typography_spectrum: 0.75109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191516'
    - '#97989d'
    - '#daae88'
    - '#d3d3d1'
  brandStrength: 0.625
  lightness: 0.30332274571992457
  saturation: 0.46898123039864004
  rhythmicContrast: 0.7356783174909651
purpose: []
