name: HouseofDB
favicon: null
layout_spectrum: 0.38579
typography_spectrum: 0.61508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191516'
    - '#97989d'
    - '#daae88'
    - '#d3d3d1'
  brandStrength: 0.875
  lightness: 0.30332274571992457
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
